name: 'CI'
on:
  pull_request: { }

jobs:
  docs-required:
    name: Documentation Required
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Validate Docs
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          pip install requests --quiet
          python $GITHUB_WORKSPACE/.github/helper/documentation.py $PR_NUMBER

  semgrep:
    name: Frappe Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download Semgrep rules
        run: git clone --depth 1 https://github.com/frappe/semgrep-rules.git frappe-semgrep-rules

      - uses: returntocorp/semgrep-action@v1
        env:
            SEMGREP_TIMEOUT: 120
        with:
            config: >-
              r/python.lang.correctness
              ./frappe-semgrep-rules/rules
