name: MariaDB

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ develop ]

concurrency:
  group: server-mariadb-develop-${{ github.event.number }}
  cancel-in-progress: true


jobs:
  determine-changes:
    name: Roulette
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.check-build.outputs.build }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - id: check-build
        run: |
          python "${GITHUB_WORKSPACE}/.github/helper/roulette.py"
        env:
          TYPE: "server"
          PR_NUMBER: ${{ github.event.number }}
          REPO_NAME: ${{ github.repository }}

  bench:
    name: Initialize Bench
    runs-on: ubuntu-latest
    needs: [ determine-changes ]
    if: ${{ needs.determine-changes.outputs.tests == 'strawberry' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Setup Dependencies
        run: |
          sudo apt-get install redis-server
          pip install frappe-bench
          bench init frappe-bench --skip-assets --python "$(which python)" --frappe-path "${GITHUB_WORKSPACE}"
          cd ./frappe-bench
          bench setup requirements --dev

      - name: Archive Bench and Dependencies
        run: tar -zcvf frappe-bench.tar.gz frappe-bench

      - uses: actions/upload-artifact@v2
        with:
          name: frappe-bench
          path: ./frappe-bench.tar.gz
          retention-days: 1

  backend-test:
    name: Python Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: [ bench ]

    strategy:
      fail-fast: false
      matrix:
       container: [1, 2]

    services:
      mysql:
        image: mariadb:10.3
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: YES
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - uses: actions/download-artifact@v2
        with:
          name: frappe-bench

      - name: Restore Bench
        run: |
          pip install frappe-bench
          tar -xvf frappe-bench.tar.gz -C /home/runner

      - name: Add to Hosts
        run: |
          echo "127.0.0.1 test_site" | sudo tee -a /etc/hosts
          echo "127.0.0.1 test_site_producer" | sudo tee -a /etc/hosts

      - name: Install
        run: bash ${GITHUB_WORKSPACE}/.github/helper/install.sh
        env:
          BEFORE: ${{ env.GITHUB_EVENT_PATH.before }}
          AFTER: ${{ env.GITHUB_EVENT_PATH.after }}
          DB: mariadb
          TYPE: server

      - name: Run Tests
        run: cd ~/frappe-bench/ && bench --site test_site run-parallel-tests --use-orchestrator --with-coverage
        env:
          CI_BUILD_ID: ${{ github.run_id }}
          ORCHESTRATOR_URL: http://test-orchestrator.frappe.io

      - name: Upload coverage data
        uses: codecov/codecov-action@v2
        with:
          name: MariaDB
          fail_ci_if_error: true
          files: ~/frappe-bench/sites/coverage.xml
          verbose: true
          flags: server

  patch-test:
    name: Patch Migration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: [ bench ]

    services:
      mysql:
        image: mariadb:10.3
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: YES
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - uses: actions/download-artifact@v2
        with:
          name: frappe-bench

      - name: Restore Bench
        run: |
          pip install frappe-bench
          tar -xvf frappe-bench.tar.gz -C /home/runner

      - name: Add to Hosts
        run: echo "127.0.0.1 test_site" | sudo tee -a /etc/hosts

      - name: Install
        run: bash ${GITHUB_WORKSPACE}/.github/helper/install.sh
        env:
          BEFORE: ${{ env.GITHUB_EVENT_PATH.before }}
          AFTER: ${{ env.GITHUB_EVENT_PATH.after }}
          DB: mariadb
          TYPE: server

      - name: Run Patch Tests
        run: |
          cd ~/frappe-bench/
          wget https://frappeframework.com/files/v10-frappe.sql.gz
          bench --site test_site --force restore ~/frappe-bench/v10-frappe.sql.gz

          source env/bin/activate
          cd apps/frappe/
          git remote set-url upstream https://github.com/frappe/frappe.git

          for version in $(seq 12 13)
          do
              echo "Updating to v$version"
              branch_name="version-$version-hotfix"
              git fetch --depth 1 upstream $branch_name:$branch_name

              git checkout -q -f $branch_name
              pip install -q -r requirements.txt
              bench --site test_site migrate
          done

          echo "Updating to last commit"
          git checkout -q -f "$GITHUB_SHA"
          bench setup requirements --python
          bench --site test_site migrate
